/**
 * Re-export the auto-generated Supabase browser client so feature code
 * imports from a stable `@/lib/supabase` path.
 *
 * Do NOT edit `src/integrations/supabase/client.ts` directly — it is
 * regenerated by Lovable Cloud.
 */
export { supabase } from "@/integrations/supabase/client";
export type { Database } from "@/integrations/supabase/types";
