/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as MyApplicationsRouteImport } from './routes/my-applications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as StudentNocRouteImport } from './routes/student/noc'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminStudentsRouteImport } from './routes/admin/students'
import { Route as AdminOpportunitiesRouteImport } from './routes/admin/opportunities'
import { Route as AdminNocRouteImport } from './routes/admin/noc'
import { Route as AdminDrivesRouteImport } from './routes/admin/drives'
import { Route as AdminCompaniesRouteImport } from './routes/admin/companies'
import { Route as AdminAllOpportunitiesRouteImport } from './routes/admin/all-opportunities'
import { Route as AdminStudentIdRouteImport } from './routes/admin/$studentId'
import { Route as AdminOpportunitiesIndexRouteImport } from './routes/admin/opportunities.index'
import { Route as AdminQuestionsOpportunityIdRouteImport } from './routes/admin/questions.$opportunityId'
import { Route as AdminOpportunitiesOpportunityIdRouteImport } from './routes/admin/opportunities.$opportunityId'
import { Route as AdminExportOpportunityIdRouteImport } from './routes/admin/export.$opportunityId'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const MyApplicationsRoute = MyApplicationsRouteImport.update({
  id: '/my-applications',
  path: '/my-applications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentNocRoute = StudentNocRouteImport.update({
  id: '/student/noc',
  path: '/student/noc',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/admin/students',
  path: '/admin/students',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOpportunitiesRoute = AdminOpportunitiesRouteImport.update({
  id: '/admin/opportunities',
  path: '/admin/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNocRoute = AdminNocRouteImport.update({
  id: '/admin/noc',
  path: '/admin/noc',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDrivesRoute = AdminDrivesRouteImport.update({
  id: '/admin/drives',
  path: '/admin/drives',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCompaniesRoute = AdminCompaniesRouteImport.update({
  id: '/admin/companies',
  path: '/admin/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAllOpportunitiesRoute = AdminAllOpportunitiesRouteImport.update({
  id: '/admin/all-opportunities',
  path: '/admin/all-opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentIdRoute = AdminStudentIdRouteImport.update({
  id: '/admin/$studentId',
  path: '/admin/$studentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOpportunitiesIndexRoute = AdminOpportunitiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminOpportunitiesRoute,
} as any)
const AdminQuestionsOpportunityIdRoute =
  AdminQuestionsOpportunityIdRouteImport.update({
    id: '/admin/questions/$opportunityId',
    path: '/admin/questions/$opportunityId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminOpportunitiesOpportunityIdRoute =
  AdminOpportunitiesOpportunityIdRouteImport.update({
    id: '/$opportunityId',
    path: '/$opportunityId',
    getParentRoute: () => AdminOpportunitiesRoute,
  } as any)
const AdminExportOpportunityIdRoute =
  AdminExportOpportunityIdRouteImport.update({
    id: '/admin/export/$opportunityId',
    path: '/admin/export/$opportunityId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/my-applications': typeof MyApplicationsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/profile': typeof ProfileRoute
  '/admin/$studentId': typeof AdminStudentIdRoute
  '/admin/all-opportunities': typeof AdminAllOpportunitiesRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/drives': typeof AdminDrivesRoute
  '/admin/noc': typeof AdminNocRoute
  '/admin/opportunities': typeof AdminOpportunitiesRouteWithChildren
  '/admin/students': typeof AdminStudentsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/student/noc': typeof StudentNocRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/export/$opportunityId': typeof AdminExportOpportunityIdRoute
  '/admin/opportunities/$opportunityId': typeof AdminOpportunitiesOpportunityIdRoute
  '/admin/questions/$opportunityId': typeof AdminQuestionsOpportunityIdRoute
  '/admin/opportunities/': typeof AdminOpportunitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/my-applications': typeof MyApplicationsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/profile': typeof ProfileRoute
  '/admin/$studentId': typeof AdminStudentIdRoute
  '/admin/all-opportunities': typeof AdminAllOpportunitiesRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/drives': typeof AdminDrivesRoute
  '/admin/noc': typeof AdminNocRoute
  '/admin/students': typeof AdminStudentsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/student/noc': typeof StudentNocRoute
  '/admin': typeof AdminIndexRoute
  '/admin/export/$opportunityId': typeof AdminExportOpportunityIdRoute
  '/admin/opportunities/$opportunityId': typeof AdminOpportunitiesOpportunityIdRoute
  '/admin/questions/$opportunityId': typeof AdminQuestionsOpportunityIdRoute
  '/admin/opportunities': typeof AdminOpportunitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/my-applications': typeof MyApplicationsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/profile': typeof ProfileRoute
  '/admin/$studentId': typeof AdminStudentIdRoute
  '/admin/all-opportunities': typeof AdminAllOpportunitiesRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/drives': typeof AdminDrivesRoute
  '/admin/noc': typeof AdminNocRoute
  '/admin/opportunities': typeof AdminOpportunitiesRouteWithChildren
  '/admin/students': typeof AdminStudentsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/student/noc': typeof StudentNocRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/export/$opportunityId': typeof AdminExportOpportunityIdRoute
  '/admin/opportunities/$opportunityId': typeof AdminOpportunitiesOpportunityIdRoute
  '/admin/questions/$opportunityId': typeof AdminQuestionsOpportunityIdRoute
  '/admin/opportunities/': typeof AdminOpportunitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/my-applications'
    | '/opportunities'
    | '/profile'
    | '/admin/$studentId'
    | '/admin/all-opportunities'
    | '/admin/companies'
    | '/admin/drives'
    | '/admin/noc'
    | '/admin/opportunities'
    | '/admin/students'
    | '/auth/callback'
    | '/student/noc'
    | '/admin/'
    | '/admin/export/$opportunityId'
    | '/admin/opportunities/$opportunityId'
    | '/admin/questions/$opportunityId'
    | '/admin/opportunities/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/my-applications'
    | '/opportunities'
    | '/profile'
    | '/admin/$studentId'
    | '/admin/all-opportunities'
    | '/admin/companies'
    | '/admin/drives'
    | '/admin/noc'
    | '/admin/students'
    | '/auth/callback'
    | '/student/noc'
    | '/admin'
    | '/admin/export/$opportunityId'
    | '/admin/opportunities/$opportunityId'
    | '/admin/questions/$opportunityId'
    | '/admin/opportunities'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/my-applications'
    | '/opportunities'
    | '/profile'
    | '/admin/$studentId'
    | '/admin/all-opportunities'
    | '/admin/companies'
    | '/admin/drives'
    | '/admin/noc'
    | '/admin/opportunities'
    | '/admin/students'
    | '/auth/callback'
    | '/student/noc'
    | '/admin/'
    | '/admin/export/$opportunityId'
    | '/admin/opportunities/$opportunityId'
    | '/admin/questions/$opportunityId'
    | '/admin/opportunities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MyApplicationsRoute: typeof MyApplicationsRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  ProfileRoute: typeof ProfileRoute
  AdminStudentIdRoute: typeof AdminStudentIdRoute
  AdminAllOpportunitiesRoute: typeof AdminAllOpportunitiesRoute
  AdminCompaniesRoute: typeof AdminCompaniesRoute
  AdminDrivesRoute: typeof AdminDrivesRoute
  AdminNocRoute: typeof AdminNocRoute
  AdminOpportunitiesRoute: typeof AdminOpportunitiesRouteWithChildren
  AdminStudentsRoute: typeof AdminStudentsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  StudentNocRoute: typeof StudentNocRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminExportOpportunityIdRoute: typeof AdminExportOpportunityIdRoute
  AdminQuestionsOpportunityIdRoute: typeof AdminQuestionsOpportunityIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-applications': {
      id: '/my-applications'
      path: '/my-applications'
      fullPath: '/my-applications'
      preLoaderRoute: typeof MyApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/noc': {
      id: '/student/noc'
      path: '/student/noc'
      fullPath: '/student/noc'
      preLoaderRoute: typeof StudentNocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/admin/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/opportunities': {
      id: '/admin/opportunities'
      path: '/admin/opportunities'
      fullPath: '/admin/opportunities'
      preLoaderRoute: typeof AdminOpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/noc': {
      id: '/admin/noc'
      path: '/admin/noc'
      fullPath: '/admin/noc'
      preLoaderRoute: typeof AdminNocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/drives': {
      id: '/admin/drives'
      path: '/admin/drives'
      fullPath: '/admin/drives'
      preLoaderRoute: typeof AdminDrivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/companies': {
      id: '/admin/companies'
      path: '/admin/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AdminCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/all-opportunities': {
      id: '/admin/all-opportunities'
      path: '/admin/all-opportunities'
      fullPath: '/admin/all-opportunities'
      preLoaderRoute: typeof AdminAllOpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$studentId': {
      id: '/admin/$studentId'
      path: '/admin/$studentId'
      fullPath: '/admin/$studentId'
      preLoaderRoute: typeof AdminStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/opportunities/': {
      id: '/admin/opportunities/'
      path: '/'
      fullPath: '/admin/opportunities/'
      preLoaderRoute: typeof AdminOpportunitiesIndexRouteImport
      parentRoute: typeof AdminOpportunitiesRoute
    }
    '/admin/questions/$opportunityId': {
      id: '/admin/questions/$opportunityId'
      path: '/admin/questions/$opportunityId'
      fullPath: '/admin/questions/$opportunityId'
      preLoaderRoute: typeof AdminQuestionsOpportunityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/opportunities/$opportunityId': {
      id: '/admin/opportunities/$opportunityId'
      path: '/$opportunityId'
      fullPath: '/admin/opportunities/$opportunityId'
      preLoaderRoute: typeof AdminOpportunitiesOpportunityIdRouteImport
      parentRoute: typeof AdminOpportunitiesRoute
    }
    '/admin/export/$opportunityId': {
      id: '/admin/export/$opportunityId'
      path: '/admin/export/$opportunityId'
      fullPath: '/admin/export/$opportunityId'
      preLoaderRoute: typeof AdminExportOpportunityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminOpportunitiesRouteChildren {
  AdminOpportunitiesOpportunityIdRoute: typeof AdminOpportunitiesOpportunityIdRoute
  AdminOpportunitiesIndexRoute: typeof AdminOpportunitiesIndexRoute
}

const AdminOpportunitiesRouteChildren: AdminOpportunitiesRouteChildren = {
  AdminOpportunitiesOpportunityIdRoute: AdminOpportunitiesOpportunityIdRoute,
  AdminOpportunitiesIndexRoute: AdminOpportunitiesIndexRoute,
}

const AdminOpportunitiesRouteWithChildren =
  AdminOpportunitiesRoute._addFileChildren(AdminOpportunitiesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MyApplicationsRoute: MyApplicationsRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  ProfileRoute: ProfileRoute,
  AdminStudentIdRoute: AdminStudentIdRoute,
  AdminAllOpportunitiesRoute: AdminAllOpportunitiesRoute,
  AdminCompaniesRoute: AdminCompaniesRoute,
  AdminDrivesRoute: AdminDrivesRoute,
  AdminNocRoute: AdminNocRoute,
  AdminOpportunitiesRoute: AdminOpportunitiesRouteWithChildren,
  AdminStudentsRoute: AdminStudentsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  StudentNocRoute: StudentNocRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminExportOpportunityIdRoute: AdminExportOpportunityIdRoute,
  AdminQuestionsOpportunityIdRoute: AdminQuestionsOpportunityIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
