/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MyApplicationsRouteImport } from './routes/my-applications'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OnboardingSubmittedRouteImport } from './routes/onboarding-submitted'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminStudentIdRouteImport } from './routes/admin/$studentId'
import { Route as AdminAllOpportunitiesRouteImport } from './routes/admin/all-opportunities'
import { Route as AdminAttendanceRouteImport } from './routes/admin/attendance'
import { Route as AdminCompaniesRouteImport } from './routes/admin/companies'
import { Route as AdminDrivesRouteImport } from './routes/admin/drives'
import { Route as AdminNocRouteImport } from './routes/admin/noc'
import { Route as AdminOnboardingApprovalsRouteImport } from './routes/admin/onboarding-approvals'
import { Route as AdminOpportunitiesRouteImport } from './routes/admin/opportunities'
import { Route as AdminRecruitmentRouteImport } from './routes/admin/recruitment'
import { Route as AdminRecruitmentExecutionRouteImport } from './routes/admin/recruitment-execution'
import { Route as AdminRecruitmentNewRouteImport } from './routes/admin/recruitment-new'
import { Route as AdminStudentsRouteImport } from './routes/admin/students'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as HodIndexRouteImport } from './routes/hod/index'
import { Route as StudentNocRouteImport } from './routes/student/noc'
import { Route as WorkspaceCatalogRouteImport } from './routes/workspace/catalog'
import { Route as WorkspaceRegistryImportRouteImport } from './routes/workspace/registry-import'
import { Route as AdminExportOpportunityIdRouteImport } from './routes/admin/export.$opportunityId'
import { Route as AdminOnboardingReviewDraftIdRouteImport } from './routes/admin/onboarding-review.$draftId'
import { Route as AdminOpportunitiesIndexRouteImport } from './routes/admin/opportunities.index'
import { Route as AdminOpportunitiesOpportunityIdRouteImport } from './routes/admin/opportunities.$opportunityId'
import { Route as AdminQuestionsOpportunityIdRouteImport } from './routes/admin/questions.$opportunityId'
import { Route as AdminRecruitmentIndexRouteImport } from './routes/admin/recruitment.index'
import { Route as AdminRecruitmentDraftIdRouteImport } from './routes/admin/recruitment.$draftId'
import { Route as HodReviewTokenRouteImport } from './routes/hod/review.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MyApplicationsRoute = MyApplicationsRouteImport.update({
  id: '/my-applications',
  path: '/my-applications',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingSubmittedRoute = OnboardingSubmittedRouteImport.update({
  id: '/onboarding-submitted',
  path: '/onboarding-submitted',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentIdRoute = AdminStudentIdRouteImport.update({
  id: '/admin/$studentId',
  path: '/admin/$studentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAllOpportunitiesRoute = AdminAllOpportunitiesRouteImport.update({
  id: '/admin/all-opportunities',
  path: '/admin/all-opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/admin/attendance',
  path: '/admin/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCompaniesRoute = AdminCompaniesRouteImport.update({
  id: '/admin/companies',
  path: '/admin/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDrivesRoute = AdminDrivesRouteImport.update({
  id: '/admin/drives',
  path: '/admin/drives',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNocRoute = AdminNocRouteImport.update({
  id: '/admin/noc',
  path: '/admin/noc',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOnboardingApprovalsRoute =
  AdminOnboardingApprovalsRouteImport.update({
    id: '/admin/onboarding-approvals',
    path: '/admin/onboarding-approvals',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminOpportunitiesRoute = AdminOpportunitiesRouteImport.update({
  id: '/admin/opportunities',
  path: '/admin/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRecruitmentRoute = AdminRecruitmentRouteImport.update({
  id: '/admin/recruitment',
  path: '/admin/recruitment',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRecruitmentExecutionRoute =
  AdminRecruitmentExecutionRouteImport.update({
    id: '/admin/recruitment-execution',
    path: '/admin/recruitment-execution',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminRecruitmentNewRoute = AdminRecruitmentNewRouteImport.update({
  id: '/admin/recruitment-new',
  path: '/admin/recruitment-new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/admin/students',
  path: '/admin/students',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const HodIndexRoute = HodIndexRouteImport.update({
  id: '/hod/',
  path: '/hod/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentNocRoute = StudentNocRouteImport.update({
  id: '/student/noc',
  path: '/student/noc',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceCatalogRoute = WorkspaceCatalogRouteImport.update({
  id: '/workspace/catalog',
  path: '/workspace/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRegistryImportRoute = WorkspaceRegistryImportRouteImport.update({
  id: '/workspace/registry-import',
  path: '/workspace/registry-import',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExportOpportunityIdRoute =
  AdminExportOpportunityIdRouteImport.update({
    id: '/admin/export/$opportunityId',
    path: '/admin/export/$opportunityId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminOnboardingReviewDraftIdRoute =
  AdminOnboardingReviewDraftIdRouteImport.update({
    id: '/admin/onboarding-review/$draftId',
    path: '/admin/onboarding-review/$draftId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminOpportunitiesIndexRoute = AdminOpportunitiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminOpportunitiesRoute,
} as any)
const AdminOpportunitiesOpportunityIdRoute =
  AdminOpportunitiesOpportunityIdRouteImport.update({
    id: '/$opportunityId',
    path: '/$opportunityId',
    getParentRoute: () => AdminOpportunitiesRoute,
  } as any)
const AdminQuestionsOpportunityIdRoute =
  AdminQuestionsOpportunityIdRouteImport.update({
    id: '/admin/questions/$opportunityId',
    path: '/admin/questions/$opportunityId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminRecruitmentIndexRoute = AdminRecruitmentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRecruitmentRoute,
} as any)
const AdminRecruitmentDraftIdRoute = AdminRecruitmentDraftIdRouteImport.update({
  id: '/$draftId',
  path: '/$draftId',
  getParentRoute: () => AdminRecruitmentRoute,
} as any)
const HodReviewTokenRoute = HodReviewTokenRouteImport.update({
  id: '/hod/review/$token',
  path: '/hod/review/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/my-applications': typeof MyApplicationsRoute
  '/onboarding': typeof OnboardingRoute
  '/onboarding-submitted': typeof OnboardingSubmittedRoute
  '/opportunities': typeof OpportunitiesRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/$studentId': typeof AdminStudentIdRoute
  '/admin/all-opportunities': typeof AdminAllOpportunitiesRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/drives': typeof AdminDrivesRoute
  '/admin/noc': typeof AdminNocRoute
  '/admin/onboarding-approvals': typeof AdminOnboardingApprovalsRoute
  '/admin/opportunities': typeof AdminOpportunitiesRouteWithChildren
  '/admin/recruitment': typeof AdminRecruitmentRouteWithChildren
  '/admin/recruitment-execution': typeof AdminRecruitmentExecutionRoute
  '/admin/recruitment-new': typeof AdminRecruitmentNewRoute
  '/admin/students': typeof AdminStudentsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/student/noc': typeof StudentNocRoute
  '/workspace/catalog': typeof WorkspaceCatalogRoute
  '/workspace/registry-import': typeof WorkspaceRegistryImportRoute
  '/admin/': typeof AdminIndexRoute
  '/hod/': typeof HodIndexRoute
  '/admin/export/$opportunityId': typeof AdminExportOpportunityIdRoute
  '/admin/onboarding-review/$draftId': typeof AdminOnboardingReviewDraftIdRoute
  '/admin/opportunities/$opportunityId': typeof AdminOpportunitiesOpportunityIdRoute
  '/admin/questions/$opportunityId': typeof AdminQuestionsOpportunityIdRoute
  '/admin/recruitment/$draftId': typeof AdminRecruitmentDraftIdRoute
  '/hod/review/$token': typeof HodReviewTokenRoute
  '/admin/opportunities/': typeof AdminOpportunitiesIndexRoute
  '/admin/recruitment/': typeof AdminRecruitmentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/my-applications': typeof MyApplicationsRoute
  '/onboarding': typeof OnboardingRoute
  '/onboarding-submitted': typeof OnboardingSubmittedRoute
  '/opportunities': typeof OpportunitiesRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/$studentId': typeof AdminStudentIdRoute
  '/admin/all-opportunities': typeof AdminAllOpportunitiesRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/drives': typeof AdminDrivesRoute
  '/admin/noc': typeof AdminNocRoute
  '/admin/onboarding-approvals': typeof AdminOnboardingApprovalsRoute
  '/admin/recruitment-execution': typeof AdminRecruitmentExecutionRoute
  '/admin/recruitment-new': typeof AdminRecruitmentNewRoute
  '/admin/students': typeof AdminStudentsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/student/noc': typeof StudentNocRoute
  '/workspace/catalog': typeof WorkspaceCatalogRoute
  '/workspace/registry-import': typeof WorkspaceRegistryImportRoute
  '/admin': typeof AdminIndexRoute
  '/hod': typeof HodIndexRoute
  '/admin/export/$opportunityId': typeof AdminExportOpportunityIdRoute
  '/admin/onboarding-review/$draftId': typeof AdminOnboardingReviewDraftIdRoute
  '/admin/opportunities/$opportunityId': typeof AdminOpportunitiesOpportunityIdRoute
  '/admin/questions/$opportunityId': typeof AdminQuestionsOpportunityIdRoute
  '/admin/recruitment/$draftId': typeof AdminRecruitmentDraftIdRoute
  '/hod/review/$token': typeof HodReviewTokenRoute
  '/admin/opportunities': typeof AdminOpportunitiesIndexRoute
  '/admin/recruitment': typeof AdminRecruitmentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/my-applications': typeof MyApplicationsRoute
  '/onboarding': typeof OnboardingRoute
  '/onboarding-submitted': typeof OnboardingSubmittedRoute
  '/opportunities': typeof OpportunitiesRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/$studentId': typeof AdminStudentIdRoute
  '/admin/all-opportunities': typeof AdminAllOpportunitiesRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/drives': typeof AdminDrivesRoute
  '/admin/noc': typeof AdminNocRoute
  '/admin/onboarding-approvals': typeof AdminOnboardingApprovalsRoute
  '/admin/opportunities': typeof AdminOpportunitiesRouteWithChildren
  '/admin/recruitment': typeof AdminRecruitmentRouteWithChildren
  '/admin/recruitment-execution': typeof AdminRecruitmentExecutionRoute
  '/admin/recruitment-new': typeof AdminRecruitmentNewRoute
  '/admin/students': typeof AdminStudentsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/student/noc': typeof StudentNocRoute
  '/workspace/catalog': typeof WorkspaceCatalogRoute
  '/workspace/registry-import': typeof WorkspaceRegistryImportRoute
  '/admin/': typeof AdminIndexRoute
  '/hod/': typeof HodIndexRoute
  '/admin/export/$opportunityId': typeof AdminExportOpportunityIdRoute
  '/admin/onboarding-review/$draftId': typeof AdminOnboardingReviewDraftIdRoute
  '/admin/opportunities/$opportunityId': typeof AdminOpportunitiesOpportunityIdRoute
  '/admin/questions/$opportunityId': typeof AdminQuestionsOpportunityIdRoute
  '/admin/recruitment/$draftId': typeof AdminRecruitmentDraftIdRoute
  '/hod/review/$token': typeof HodReviewTokenRoute
  '/admin/opportunities/': typeof AdminOpportunitiesIndexRoute
  '/admin/recruitment/': typeof AdminRecruitmentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/my-applications'
    | '/onboarding'
    | '/onboarding-submitted'
    | '/opportunities'
    | '/profile'
    | '/reset-password'
    | '/admin/$studentId'
    | '/admin/all-opportunities'
    | '/admin/attendance'
    | '/admin/companies'
    | '/admin/drives'
    | '/admin/noc'
    | '/admin/onboarding-approvals'
    | '/admin/opportunities'
    | '/admin/recruitment'
    | '/admin/recruitment-execution'
    | '/admin/recruitment-new'
    | '/admin/students'
    | '/auth/callback'
    | '/student/noc'
    | '/workspace/catalog'
    | '/workspace/registry-import'
    | '/admin/'
    | '/hod/'
    | '/admin/export/$opportunityId'
    | '/admin/onboarding-review/$draftId'
    | '/admin/opportunities/$opportunityId'
    | '/admin/questions/$opportunityId'
    | '/admin/recruitment/$draftId'
    | '/hod/review/$token'
    | '/admin/opportunities/'
    | '/admin/recruitment/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/my-applications'
    | '/onboarding'
    | '/onboarding-submitted'
    | '/opportunities'
    | '/profile'
    | '/reset-password'
    | '/admin/$studentId'
    | '/admin/all-opportunities'
    | '/admin/attendance'
    | '/admin/companies'
    | '/admin/drives'
    | '/admin/noc'
    | '/admin/onboarding-approvals'
    | '/admin/recruitment-execution'
    | '/admin/recruitment-new'
    | '/admin/students'
    | '/auth/callback'
    | '/student/noc'
    | '/workspace/catalog'
    | '/workspace/registry-import'
    | '/admin'
    | '/hod'
    | '/admin/export/$opportunityId'
    | '/admin/onboarding-review/$draftId'
    | '/admin/opportunities/$opportunityId'
    | '/admin/questions/$opportunityId'
    | '/admin/recruitment/$draftId'
    | '/hod/review/$token'
    | '/admin/opportunities'
    | '/admin/recruitment'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/my-applications'
    | '/onboarding'
    | '/onboarding-submitted'
    | '/opportunities'
    | '/profile'
    | '/reset-password'
    | '/admin/$studentId'
    | '/admin/all-opportunities'
    | '/admin/attendance'
    | '/admin/companies'
    | '/admin/drives'
    | '/admin/noc'
    | '/admin/onboarding-approvals'
    | '/admin/opportunities'
    | '/admin/recruitment'
    | '/admin/recruitment-execution'
    | '/admin/recruitment-new'
    | '/admin/students'
    | '/auth/callback'
    | '/student/noc'
    | '/workspace/catalog'
    | '/workspace/registry-import'
    | '/admin/'
    | '/hod/'
    | '/admin/export/$opportunityId'
    | '/admin/onboarding-review/$draftId'
    | '/admin/opportunities/$opportunityId'
    | '/admin/questions/$opportunityId'
    | '/admin/recruitment/$draftId'
    | '/hod/review/$token'
    | '/admin/opportunities/'
    | '/admin/recruitment/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MyApplicationsRoute: typeof MyApplicationsRoute
  OnboardingRoute: typeof OnboardingRoute
  OnboardingSubmittedRoute: typeof OnboardingSubmittedRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AdminStudentIdRoute: typeof AdminStudentIdRoute
  AdminAllOpportunitiesRoute: typeof AdminAllOpportunitiesRoute
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminCompaniesRoute: typeof AdminCompaniesRoute
  AdminDrivesRoute: typeof AdminDrivesRoute
  AdminNocRoute: typeof AdminNocRoute
  AdminOnboardingApprovalsRoute: typeof AdminOnboardingApprovalsRoute
  AdminOpportunitiesRoute: typeof AdminOpportunitiesRouteWithChildren
  AdminRecruitmentRoute: typeof AdminRecruitmentRouteWithChildren
  AdminRecruitmentExecutionRoute: typeof AdminRecruitmentExecutionRoute
  AdminRecruitmentNewRoute: typeof AdminRecruitmentNewRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  StudentNocRoute: typeof StudentNocRoute
  WorkspaceCatalogRoute: typeof WorkspaceCatalogRoute
  WorkspaceRegistryImportRoute: typeof WorkspaceRegistryImportRoute
  AdminIndexRoute: typeof AdminIndexRoute
  HodIndexRoute: typeof HodIndexRoute
  AdminExportOpportunityIdRoute: typeof AdminExportOpportunityIdRoute
  AdminOnboardingReviewDraftIdRoute: typeof AdminOnboardingReviewDraftIdRoute
  AdminQuestionsOpportunityIdRoute: typeof AdminQuestionsOpportunityIdRoute
  HodReviewTokenRoute: typeof HodReviewTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-applications': {
      id: '/my-applications'
      path: '/my-applications'
      fullPath: '/my-applications'
      preLoaderRoute: typeof MyApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding-submitted': {
      id: '/onboarding-submitted'
      path: '/onboarding-submitted'
      fullPath: '/onboarding-submitted'
      preLoaderRoute: typeof OnboardingSubmittedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$studentId': {
      id: '/admin/$studentId'
      path: '/admin/$studentId'
      fullPath: '/admin/$studentId'
      preLoaderRoute: typeof AdminStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/all-opportunities': {
      id: '/admin/all-opportunities'
      path: '/admin/all-opportunities'
      fullPath: '/admin/all-opportunities'
      preLoaderRoute: typeof AdminAllOpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/admin/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/companies': {
      id: '/admin/companies'
      path: '/admin/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AdminCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/drives': {
      id: '/admin/drives'
      path: '/admin/drives'
      fullPath: '/admin/drives'
      preLoaderRoute: typeof AdminDrivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/noc': {
      id: '/admin/noc'
      path: '/admin/noc'
      fullPath: '/admin/noc'
      preLoaderRoute: typeof AdminNocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/onboarding-approvals': {
      id: '/admin/onboarding-approvals'
      path: '/admin/onboarding-approvals'
      fullPath: '/admin/onboarding-approvals'
      preLoaderRoute: typeof AdminOnboardingApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/opportunities': {
      id: '/admin/opportunities'
      path: '/admin/opportunities'
      fullPath: '/admin/opportunities'
      preLoaderRoute: typeof AdminOpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/recruitment': {
      id: '/admin/recruitment'
      path: '/admin/recruitment'
      fullPath: '/admin/recruitment'
      preLoaderRoute: typeof AdminRecruitmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/recruitment-execution': {
      id: '/admin/recruitment-execution'
      path: '/admin/recruitment-execution'
      fullPath: '/admin/recruitment-execution'
      preLoaderRoute: typeof AdminRecruitmentExecutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/recruitment-new': {
      id: '/admin/recruitment-new'
      path: '/admin/recruitment-new'
      fullPath: '/admin/recruitment-new'
      preLoaderRoute: typeof AdminRecruitmentNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/admin/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hod/': {
      id: '/hod/'
      path: '/hod'
      fullPath: '/hod/'
      preLoaderRoute: typeof HodIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/noc': {
      id: '/student/noc'
      path: '/student/noc'
      fullPath: '/student/noc'
      preLoaderRoute: typeof StudentNocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/catalog': {
      id: '/workspace/catalog'
      path: '/workspace/catalog'
      fullPath: '/workspace/catalog'
      preLoaderRoute: typeof WorkspaceCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/registry-import': {
      id: '/workspace/registry-import'
      path: '/workspace/registry-import'
      fullPath: '/workspace/registry-import'
      preLoaderRoute: typeof WorkspaceRegistryImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/export/$opportunityId': {
      id: '/admin/export/$opportunityId'
      path: '/admin/export/$opportunityId'
      fullPath: '/admin/export/$opportunityId'
      preLoaderRoute: typeof AdminExportOpportunityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/onboarding-review/$draftId': {
      id: '/admin/onboarding-review/$draftId'
      path: '/admin/onboarding-review/$draftId'
      fullPath: '/admin/onboarding-review/$draftId'
      preLoaderRoute: typeof AdminOnboardingReviewDraftIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/opportunities/': {
      id: '/admin/opportunities/'
      path: '/'
      fullPath: '/admin/opportunities/'
      preLoaderRoute: typeof AdminOpportunitiesIndexRouteImport
      parentRoute: typeof AdminOpportunitiesRoute
    }
    '/admin/opportunities/$opportunityId': {
      id: '/admin/opportunities/$opportunityId'
      path: '/$opportunityId'
      fullPath: '/admin/opportunities/$opportunityId'
      preLoaderRoute: typeof AdminOpportunitiesOpportunityIdRouteImport
      parentRoute: typeof AdminOpportunitiesRoute
    }
    '/admin/questions/$opportunityId': {
      id: '/admin/questions/$opportunityId'
      path: '/admin/questions/$opportunityId'
      fullPath: '/admin/questions/$opportunityId'
      preLoaderRoute: typeof AdminQuestionsOpportunityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/recruitment/': {
      id: '/admin/recruitment/'
      path: '/'
      fullPath: '/admin/recruitment/'
      preLoaderRoute: typeof AdminRecruitmentIndexRouteImport
      parentRoute: typeof AdminRecruitmentRoute
    }
    '/admin/recruitment/$draftId': {
      id: '/admin/recruitment/$draftId'
      path: '/$draftId'
      fullPath: '/admin/recruitment/$draftId'
      preLoaderRoute: typeof AdminRecruitmentDraftIdRouteImport
      parentRoute: typeof AdminRecruitmentRoute
    }
    '/hod/review/$token': {
      id: '/hod/review/$token'
      path: '/hod/review/$token'
      fullPath: '/hod/review/$token'
      preLoaderRoute: typeof HodReviewTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminOpportunitiesRouteChildren {
  AdminOpportunitiesOpportunityIdRoute: typeof AdminOpportunitiesOpportunityIdRoute
  AdminOpportunitiesIndexRoute: typeof AdminOpportunitiesIndexRoute
}

const AdminOpportunitiesRouteChildren: AdminOpportunitiesRouteChildren = {
  AdminOpportunitiesOpportunityIdRoute: AdminOpportunitiesOpportunityIdRoute,
  AdminOpportunitiesIndexRoute: AdminOpportunitiesIndexRoute,
}

const AdminOpportunitiesRouteWithChildren =
  AdminOpportunitiesRoute._addFileChildren(AdminOpportunitiesRouteChildren)

interface AdminRecruitmentRouteChildren {
  AdminRecruitmentDraftIdRoute: typeof AdminRecruitmentDraftIdRoute
  AdminRecruitmentIndexRoute: typeof AdminRecruitmentIndexRoute
}

const AdminRecruitmentRouteChildren: AdminRecruitmentRouteChildren = {
  AdminRecruitmentDraftIdRoute: AdminRecruitmentDraftIdRoute,
  AdminRecruitmentIndexRoute: AdminRecruitmentIndexRoute,
}

const AdminRecruitmentRouteWithChildren =
  AdminRecruitmentRoute._addFileChildren(AdminRecruitmentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MyApplicationsRoute: MyApplicationsRoute,
  OnboardingRoute: OnboardingRoute,
  OnboardingSubmittedRoute: OnboardingSubmittedRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AdminStudentIdRoute: AdminStudentIdRoute,
  AdminAllOpportunitiesRoute: AdminAllOpportunitiesRoute,
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminCompaniesRoute: AdminCompaniesRoute,
  AdminDrivesRoute: AdminDrivesRoute,
  AdminNocRoute: AdminNocRoute,
  AdminOnboardingApprovalsRoute: AdminOnboardingApprovalsRoute,
  AdminOpportunitiesRoute: AdminOpportunitiesRouteWithChildren,
  AdminRecruitmentRoute: AdminRecruitmentRouteWithChildren,
  AdminRecruitmentExecutionRoute: AdminRecruitmentExecutionRoute,
  AdminRecruitmentNewRoute: AdminRecruitmentNewRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  StudentNocRoute: StudentNocRoute,
  WorkspaceCatalogRoute: WorkspaceCatalogRoute,
  WorkspaceRegistryImportRoute: WorkspaceRegistryImportRoute,
  AdminIndexRoute: AdminIndexRoute,
  HodIndexRoute: HodIndexRoute,
  AdminExportOpportunityIdRoute: AdminExportOpportunityIdRoute,
  AdminOnboardingReviewDraftIdRoute: AdminOnboardingReviewDraftIdRoute,
  AdminQuestionsOpportunityIdRoute: AdminQuestionsOpportunityIdRoute,
  HodReviewTokenRoute: HodReviewTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
